# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20161227_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kirrurl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
